// File generated by FlutterFire CLI.
// This is a placeholder/mock configuration for Firebase
// In production, replace this with actual Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmock-web-api-key-placeholder',
    appId: '1:123456789:web:abc123placeholder',
    messagingSenderId: '123456789',
    projectId: 'sihati-placeholder',
    authDomain: 'sihati-placeholder.firebaseapp.com',
    storageBucket: 'sihati-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmock-android-api-key-placeholder',
    appId: '1:123456789:android:abc123placeholder',
    messagingSenderId: '123456789',
    projectId: 'sihati-placeholder',
    storageBucket: 'sihati-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmock-ios-api-key-placeholder',
    appId: '1:123456789:ios:abc123placeholder',
    messagingSenderId: '123456789',
    projectId: 'sihati-placeholder',
    storageBucket: 'sihati-placeholder.appspot.com',
    iosBundleId: 'com.example.sihati',
  );
}
